version: "3.8"
services:
  item-app:
    image: "bagassetia/item-app:v1"
    command: sh -c "npm install && npm start"
    ports: 
      - 80:8080
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - item-db
  item-db:
    image: "mongo:3"
    volumes:
      - app-db:/data/db
volumes:
  app-db: